# Generated by Django 4.0.2 on 2022-02-13 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bubl_month_schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_bubl', models.JSONField()),
                ('month_bubl', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='bubl_schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='bubl_template',
            fields=[
                ('task_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=64)),
                ('bubl_template', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('email', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('dob', models.DateField()),
                ('time_zone', models.IntegerField()),
                ('retention_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='user_login',
            fields=[
                ('user_name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=64)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user_data')),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='bubl_template',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user_data'),
        ),
        migrations.AddField(
            model_name='bubl_schedule',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user_data'),
        ),
        migrations.AddField(
            model_name='bubl_month_schedule',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user_data'),
        ),
    ]
