# Generated by Django 4.0.2 on 2022-02-24 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bubl_month_schedule_bubl_schedule_bubl_template_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BublMonthSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_bubl', models.JSONField()),
                ('month_bubl', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='BublSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='BublTemplate',
            fields=[
                ('task_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=64)),
                ('bubl_template', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('email', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('user_name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=64)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userdata')),
            ],
        ),
        migrations.RemoveField(
            model_name='bubl_schedule',
            name='email',
        ),
        migrations.RemoveField(
            model_name='bubl_template',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user_login',
            name='email',
        ),
        migrations.DeleteModel(
            name='bubl_month_schedule',
        ),
        migrations.DeleteModel(
            name='bubl_schedule',
        ),
        migrations.DeleteModel(
            name='bubl_template',
        ),
        migrations.DeleteModel(
            name='user_data',
        ),
        migrations.DeleteModel(
            name='user_login',
        ),
        migrations.AddField(
            model_name='bubltemplate',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userdata'),
        ),
        migrations.AddField(
            model_name='bublschedule',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userdata'),
        ),
        migrations.AddField(
            model_name='bublmonthschedule',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userdata'),
        ),
    ]
